### ISSUE TITLE
Error attaching event log 

### ISSUE THREAD

**Issue by timgaunt** [CaptiveAire/Seq.App.YouTrack#6]
System.MissingMethodException: Method not found: 'Serilog.ILogger Serilog.LoggerConfiguration.CreateLogger()'.
   at Seq.App.YouTrack.YouTrackIssuePoster.GetJsonEventFile(Event`1 evt, String issueNumber)
   at Seq.App.YouTrack.YouTrackIssuePoster.On(Event`1 event) in C:\projects\seq-app-youtrack\src\YouTrackIssuePoster.cs:line 103

**Comment by Jaben** [comment]
Which version of Seq?

**Comment by timgaunt** [comment]
This is/was on v4.0.60

**Comment by Jaben** [comment]
Released v1.1.2 with updated dependencies.
